### ISSUE TITLE
Drunk water question

### ISSUE THREAD

**Issue by jacksonbrumbaugh** [BlakeBarrett/snse-android#6]
// apologies up front, tis my 1st ever _issue_

On the screenshot that reads "have you drunk water recently",

I'd recom being more specific

Ex : "have you had water in the past hour?"

Also, since the expected set of responses is {yes, no}, show that set as 2 btns instead of a check box

Best wishes!

**Comment by BlakeBarrett** [comment]
Thank you for your feedback @jacksonbrumbaugh; I'm so glad you find Snse helpful!

I have left all the prompts open ended because each human is different, and what may be acceptable to someone may feel different to someone else. An example of this is why there isn't any specific number assigned to the feeling-intensity slider -- since this is entirely subjective, there isn't a scientific difference between 74 and 76%; same goes for water. Someone who lives in a hot dry climate may need more water and feel like a few sips per hour is enough despite still dehydrating. 
The purpose of each of the prompts is to cause the user to check-in with themselves. 
For the question of have you recently drunk water, I was intending to get the user to actually notice how their body is feeling and if they are in a grump-mood perhaps they have drunk a little water recently, but they need more.

Making it a check-box `[√]` instead of a segmented control `[yes|no]` just allows me to have a `null` state where if the user doesn't answer the question, I don't save that field and assume `false` if empty.

**Comment by BlakeBarrett** [comment]
I will take your feedback into consideration.
If you would like to propose what changes to the UI you'd like to see in the next version, I'll be writing it using the [Flutter](https://flutter.dev) framework. You can make mockups of whatever you'd like to see on [FlutterFlow.io](https://flutterflow.io) and send them to me (either post in here, or create a PR) and I can see about incorporating that into the next version.

**Comment by jacksonbrumbaugh** [comment]
Why thank u!

Haha I am still quite new $here using GitHub, so apologies for any non-conventional approaches (=
